"""empty message

Revision ID: 26fa96677058
Revises: 88bd24890e24
Create Date: 2023-07-19 20:25:25.140794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fa96677058'
down_revision = '88bd24890e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
