"""Initial migration.

Revision ID: 69b47c401f88
Revises: a3b0aee305b6
Create Date: 2023-07-18 23:04:58.735977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b47c401f88'
down_revision = 'a3b0aee305b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('apellidos2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('residencia', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('celular', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('confirmpassword', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('imagen_perfil', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['confirmpassword'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('date_added')
        batch_op.drop_column('imagen_perfil')
        batch_op.drop_column('confirmpassword')
        batch_op.drop_column('password')
        batch_op.drop_column('celular')
        batch_op.drop_column('residencia')
        batch_op.drop_column('apellidos2')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('username')

    op.drop_table('post')
    # ### end Alembic commands ###
