"""Initial migration.

Revision ID: f1b178de0356
Revises: 69b47c401f88
Create Date: 2023-07-18 23:09:49.375949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b178de0356'
down_revision = '69b47c401f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('apellidos', sa.String(length=20), nullable=True),
    sa.Column('apellidos2', sa.String(length=20), nullable=True),
    sa.Column('residencia', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('confirmpassword', sa.String(length=60), nullable=False),
    sa.Column('imagen_perfil', sa.String(length=20), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmpassword'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
